### ISSUE TITLE
Start Screen UI changes

### ISSUE THREAD

**Issue by RajuKoushik** [aviaryan/Hinix#13]
The Start Screen User Interface could be made more materialistic and clean.The UI elements must be positioned appropriately.

**Comment by Akatsuki06** [comment]
I will do this :)

**Comment by aviaryan** [comment]
Please proceed. Be sure to include a screenshot of the start screen in your PR so that we can evaluate it correctly.

**Comment by Akatsuki06** [comment]
i have done that
![screenshot](https://cloud.githubusercontent.com/assets/16136908/19341097/a85a4ca2-9149-11e6-8627-462144594da9.png)

**Comment by salRoid** [comment]
okay what about the icon and background image , should change it or leave as it is

**Comment by aviaryan** [comment]
@salRoid Let's leave it as it is for now.

**Comment by aviaryan** [comment]
Hi @Akatsuki06 . 
We appreciate your hard work but we are not happy with the design as it doesn't integrate well with the rest of our application. Also this issue is not very subjective/quantifiable on what are the design requirements so I think it is best if it is closed now. It would be better if we make the design improvements ourselves because that would yield more suitable results. (results that are more acceptable to the team)
I hope you understand.
Thank you.
